spring:
  application:
    name: consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: default-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.kafka.consumer.dto, com.example.kafka.producer.dto, java.util
        spring.json.type.mapping: com.example.kafka.producer.dto.MessageDTO:com.example.kafka.consumer.dto.MessageDTO
server:
  port: 8082

